### ISSUE TITLE
Redirect bigtestjs.com to bigtestjs.io

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#11]
This is something one of us in FS need to do.

**Comment by cowboyd** [comment]
See https://support.dnsimple.com/articles/redirector/ for deets.

**Comment by Robdel12** [comment]
Done! Proof:
![2018-04-28 19 30 41](https://user-images.githubusercontent.com/2072894/39402034-b1f1b2c8-4b1a-11e8-8f5d-9f8bfef304ed.gif)
