### ISSUE TITLE
Create a quick start guide

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#14]
## Purpose

Create a quick start guide for BigTest. If you would like to help with this issue I'm available to explain anything you might have questions with! 

A possible outline for the quick start guide could be:

- Briefly explain the benefits of BigTest
- Give a TL;DR maybe?
	- Render your app into a browser with karma, drive the app around on the page with interactor, and assert change with mocha/chai
- Explain what a convergence is
- Explain what an interactor is
- Create an outline of tasks being covered in the quick start (a little overview)
- Go over configuring the test setup with:
	- Karma
		- Mention the `tests/index.js` fix. (We create an index file that creates a single bundle of all test files to avoid duplicate react instances inside the react test container)
	- Webpack
		- Possibly mention what karma-webpack is doing
		- Mention something about issue for integrating with other build tools
	- React
		- Building the application test harness
	- @bigtest/mirage
		- how to mock a single end point
		- create a factory for the end point
	- @bigtest/mocha
		- chai
- Writing your first test
- Integrating with your apps router
	- Offer integration with React Router
- Write test that navigates
- Write a test that mocks data with mirage
- Wrap up

We should provide an example application which we wrap tests around.

**Comment by kevoneil** [comment]
@Robdel12 Would like to help out in any way I can!

**Comment by cowboyd** [comment]
Hi @kevoneil I wonder if the first start would be getting to experience the "Quick Start" for yourself and then writing about the experience.

**Comment by kevoneil** [comment]
@cowboyd Sounds like a good idea; will try to get it set up over the weekend.

**Comment by Robdel12** [comment]
Hey @kevoneil! Super happy I was able to meet you in person last week at JSConf! 🎉 

I want to get the `@bigtest/cli` fleshed out before we start working on the quick start guide together. We'll be using the `init` and `run` commands I talked about in my presentation but they're not _quite_ there yet. We're close! 

If you wanted to jump onto a call to get your bearings on the project I'd be more than happy to do that too :)

**Comment by Robdel12** [comment]
Woop! We just shipped an initial version of the BigTest CLI. 🎉  So whenever you want to jump into a call and pair on this @kevoneil I'm game 😈

**Comment by kevoneil** [comment]
@Robdel12 Awesome!

I'm trying to get BigTest up and running [here](https://github.com/kevoneil/bigtest-example)! Going to try to finish this week if I can.

**Comment by kevoneil** [comment]
Sorry, just saw your first response:

> Hey @kevoneil! Super happy I was able to meet you in person last week at JSConf! 🎉

Same

> If you wanted to jump onto a call to get your bearings on the project I'd be more than happy to do that too :)

Sounds good, sent you a DM on Twitter.

**Comment by SamKeathley** [comment]
Heya, @kevoneil! I'm also going to be taking on these guides. Would you be interested in collaborating this week? I'm super interested in seeing what you've written so far and where you're heading. :)

**Comment by kevoneil** [comment]
@SamKeathley Sure! I can push up what i have on my forked repo if that's okay. 😄 

Only added the installation part so far though.

**Comment by SamKeathley** [comment]
@kevoneil Awesome! Thanks, man!

**Comment by kevoneil** [comment]
@Robdel12 Works for me! Sorry about the late reply.

**Comment by Robdel12** [comment]
Shipped the first iteration with #48 🎉
