### ISSUE TITLE
Create a guides index page

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#16]
## Purpose 

Create an index page for the guides page. This issue will also probably setup the layout for the page. I imagine we'll have a layout similar to the docs pages (with a sidebar). 

This issue is pretty open. Whatever you feel is the most helpful for a guides index. I'd start off doing research on what makes a good index.

**Comment by wwilsman** [comment]
The intro was intended to be the "index" for guides. But maybe the content on those two pages differ enough to warrant an actual index?
