### ISSUE TITLE
Create introduction guide

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#18]
## Purpose

Create an introduction guide for BigTest explaining the following:

- [x] Why BigTest? / What does BigTest do different?
- [x] Testing philosophy 
- [x] Convergence 
- [ ] Speed benefits
- [x] Interactor 
- [x] CLI
- [ ] Mirage 
- [x] Comparison to competitors 
- [ ] How to select from the DOM (ex: `data-test-app-my-select`)

**Comment by Robdel12** [comment]
With #48 almost ready to go I've updated the body of the original issue to be todo items. Most of them are checked off and completed by #48 but a few didn't make it:

- Speed benefits
- Mirage
- How to select from the DOM

**Speed benefits**
I think we could cover the speed benefits for sure. I don't think it should block shipping the initial guide but we should work it in soon.

**Mirage**
I completely skipped this because it's not _really_ our package and I don't want to write a bunch of docs for something we're planning on moving from in the future anyways. The ember-cli-mirage docs are good enough and I'll be happy to assist anyone that needs help 😊

**How to select from the DOM**
This just seems perfect for our future FAQ & didn't really fit into the introduction.

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
