### ISSUE TITLE
Create link to "edit this page on github"

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#20]
## Purpose 

I love when docs sites make it _really_ easy for me to edit their docs. For our guides at least we should offer this functionality. 

The docs for the packages will probably be a little tricker so that can be a follow up issue if that's the case. 

## Approach

I'd probably create a helper that links to that page in the source (`https://github.com/bigtestjs/bigtestjs.io/blob/master/source/${my-path-here}`). 

A nice benefit of middleman is the path you see in the browser is will match the url above because the structure of inside of the `source` folder is the structure of the URL.

**Comment by Robdel12** [comment]
It would also be nice to add the version number of the package with this ticket too. If not we can spin it out into its own issue after this is completed

**Comment by co16353sidak** [comment]
Would love to work on this @Robdel12, please give the go ahead for the same 🥇

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
