### ISSUE TITLE
Homepage CTA paragraphs

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#25]
The homepage call to action paragraphs need icons & links (an actual CTA) to their respective guides for each section. This is what it currently looks like:

![image](https://user-images.githubusercontent.com/2072894/39430394-5824fec8-4c53-11e8-9b6e-d96785ff6e8c.png)

**Comment by co16353sidak** [comment]
Would love to work on this @Robdel12 as my first issue here ?

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
