### ISSUE TITLE
Create better API docs index

### ISSUE THREAD

**Issue by wwilsman** [bigtestjs/bigtestjs.io#26]
We could use this index as a place to explain the process behind how the docs are generated.

**Comment by Robdel12** [comment]
If this is going to be a quest issue it should have enough info for anyone to be able to pick it up and do something with. I know the other ones aren't fully fleshed out yet but that's the goal for them.

**Comment by wwilsman** [comment]
Things to include on this page would be

- We use JSDoc to generate a JSON file for a package.
- We filter out private functions that don't belong to a class, such as utils.
- Middleman uses this data to generate this portion of the site.
- Above the explanation, we could also have a short summary about each package and link to it's repo and docs.

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
