### ISSUE TITLE
Figure out how to get builds to come from bigtest-bot

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#29]
Currently review app & master deploys are coming from my account. It'd be dope to have those come from bigtest-bot.

I think we're going to have to create a bigtest-bot user account for heroku & then resetup the pipeline with that account.

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
