### ISSUE TITLE
Guide for a golden path tutorial

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#3]
A general introduction to BigTest, what's different, what makes it special, and understanding the key concepts. 🔑

**Comment by co16353sidak** [comment]
Would love to work on this @Robdel12 as my first issue here.

**Comment by cowboyd** [comment]
@co16353sidak I'd be happy to help you with this.

**Comment by co16353sidak** [comment]
@cowboyd How should I go about with the process here.

**Comment by maximilianotulian** [comment]
Hey @Robdel12, Can I work on this one?

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
