### ISSUE TITLE
Docs sidebar sticky on scroll

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#32]
When scrolling through the list of docs it would be nice for the sidebar where all of the methods, functions, and properties live to scroll with you.

Currently:
![2018-05-05 11 02 02](https://user-images.githubusercontent.com/2072894/39665082-dbe8cd8a-5053-11e8-8fcb-1df13c1fffd3.gif)

What the fix _could_ look like:
![2018-05-05 11 25 10](https://user-images.githubusercontent.com/2072894/39665299-22d90130-5057-11e8-9669-edc17a4ad690.gif)

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
