### ISSUE TITLE
Adjust scroll position when clicking doc sidebar

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#33]
When you click a doc in the sidebar it's going to scroll to that doc on the page. Most of the time the title of the doc is covered up by the sticky header which makes it so I have to scroll up a bit to make sure it's the right doc. 

Here's a gif example of it:
![2018-05-05 11 18 28](https://user-images.githubusercontent.com/2072894/39665263-a8d6e6cc-5056-11e8-884c-49d441a40338.gif)

**Comment by wwilsman** [comment]
Fixed with #41
