### ISSUE TITLE
Add service worker to cache docs & go offline first

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#34]
It would be really cool for us to cache the BigTest docs offline first so you don't have to have network connection to view our documentation. 

This ticket should be implemented _after_ #28. We must set up cache busting so users don't permanently get stuck with an old version of the docs site. 

This is a pretty good resource I found for implementing a service worker for offline first if you haven't done it before: https://css-tricks.com/serviceworker-for-offline/

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
