### ISSUE TITLE
Function argument defaults are not displayed

### ISSUE THREAD

**Issue by wwilsman** [bigtestjs/bigtestjs.io#35]
For example, this documentation specifies a default value, but the website does not currently display this information

```javascript
/**
 * @param {String} [arg="default value"] - An optional argument with a default value
 */
```

**Comment by wwilsman** [comment]
In general, the API docs do not say when an argument is optional

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
