### ISSUE TITLE
Explain the philosophy behind BigTest

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#38]
It would be helpful for new comers to understand what is driving us to build this, where we came from, and what we're looking to achieve with BigTest.

**Comment by wwilsman** [comment]
:100:

This would be good to either add a section to the home page, or change that "quick start" button to "getting started" and we can add this explanation to #18. (It actually looks like those bullets include a "why" which aligns with this issue)

**Comment by Robdel12** [comment]
BAM, that sounds perfect. I'm going to set my sights on BigTest guides / docs after everything settles down.

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
