### ISSUE TITLE
Specify Interactor default scope in introduction

### ISSUE THREAD

**Issue by wwilsman** [bigtestjs/bigtestjs.io#45]
I've noticed when others are using interactors, they tend to leave out the scope selector and instead of using `defaultScope`, they specify the root selector in _every property_. 

This sometimes makes it impossible for those interactors to be reusable. Since people don't know that the scope defaults to `document.body`, there are instances where attempting to reuse those interactors results in only the first instance of those elements ever being interacted with.

Right after the introduction example, we should specify what happens when you do not specify a selector. And in the custom interactors guide, we should strongly suggest to **not** specify the root selector for every property. For example: "if you find yourself repeating the same selector in your properties, try composing an interactor scoped specifically to that selector instead."

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
