### ISSUE TITLE
Add issue / PR template

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#5]
I'm not sure if we have a standardized template. Maybe we can adapt something from x-select? https://github.com/thefrontside/emberx-select/blob/master/.github/ISSUE_TEMPLATE.md

(moved from https://github.com/thefrontside/bigtest/issues/78)

**Comment by cowboyd** [comment]
I put a lot of effort into https://raw.githubusercontent.com/folio-org/ui-eholdings/master/PULL_REQUEST_TEMPLATE.md So that the PR template would provide context in the same way that we ask our PR authors to do so.

**Comment by cowboyd** [comment]
Also, feels like we ought to be have some sort of meta project maintenance software that we can use to align all our repos.

**Comment by Robdel12** [comment]
There's a Probot for that. http://probot.github.io/apps/settings

I've been wanting to give it a go and keep that config yml in our wumbo repo.

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
