### ISSUE TITLE
Update title of page when on docs

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#50]
Currently when you're on a specific docs page (interactor for example) the title doesn't reflect that. It just says "BigTest". The title could be a little more helpful here.

![image](https://user-images.githubusercontent.com/2072894/46434221-a9665a80-c718-11e8-95c8-14ed92b42152.png)

**Comment by wwilsman** [comment]
To assist the future contributor:

[The main layout](https://github.com/bigtestjs/bigtestjs.io/blob/master/source/layouts/layout.erb#L21) already has the code necessary for this.

[The docs proxy locals](https://github.com/bigtestjs/bigtestjs.io/blob/master/config.rb#L48) will need to be updated to include a `title` (I think).
