### ISSUE TITLE
Blog / Media Page

### ISSUE THREAD

**Issue by wwilsman** [bigtestjs/bigtestjs.io#56]
We need somewhere to link out to things written about BigTest. Until that is built, let's put links here to existing content.

- https://frontside.io/blog/2018/06/13/big-testing-in-react/
- https://medium.com/@robdel12/jest-bigtest-interactor-component-test-%EF%B8%8F-11b1947954c8

**Comment by jorgelainfiesta** [comment]
This website is now archived. Please refer to [BigTest's monorepo](https://github.com/thefrontside/bigtest) for up to date information.
