### ISSUE TITLE
Update @bigtest/interactor docs 

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/bigtestjs.io#8]
The `@bigtest/interactor` docs need work. The documentation is there, but the tags are incomplete, causing the pages to render with weird and missing content.

Follow up from #6

**Comment by Robdel12** [comment]
@wwilsman I wanna tackle this one, but I think I need 10-15mins of your time to get rolling on this. I'm not sure what the docs script wants or why a lot of the docs are missing.

**Comment by wwilsman** [comment]
I'm down to pair on this whenever. We need to clean those docs up pronto!

**Comment by Robdel12** [comment]
Not sure when but I'd like to for sure

**Comment by Robdel12** [comment]
Closed with #30
